// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCqY2y4ez0jAl30p9DLtpLSMV7AzI-xM',
    appId: '1:656324666081:web:e2e5c9078115fe54364da0',
    messagingSenderId: '656324666081',
    projectId: 'golf-go-18da2',
    authDomain: 'golf-go-18da2.firebaseapp.com',
    storageBucket: 'golf-go-18da2.firebasestorage.app',
    measurementId: 'G-FT7NENDBKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCGMyAcUVnwHYlFZGJVy0CIUgVQBOcNk',
    appId: '1:656324666081:android:f9fb4776ef83d2bc364da0',
    messagingSenderId: '656324666081',
    projectId: 'golf-go-18da2',
    storageBucket: 'golf-go-18da2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5iCUFYl6ekMoJ-tTk5nZ0Gnk_pNkOaA',
    appId: '1:656324666081:ios:f13afc72238be78f364da0',
    messagingSenderId: '656324666081',
    projectId: 'golf-go-18da2',
    storageBucket: 'golf-go-18da2.firebasestorage.app',
    iosClientId: '656324666081-2gf08fqlqmldo89ca9n3aki534s4vrpc.apps.googleusercontent.com',
    iosBundleId: 'com.golfgo.app',
  );

}